version: 2.1

workflows:
   build_and_test:
     jobs:
       - scala:
           name: Scala 2.12.x with Akka 2.5.x
           scala_version: 2.12.13
       - scala:
           name: Scala 2.13.x with Akka 2.5.x
           scala_version: 2.13.5
       - scala:
           name: Scala 2.13.x with Akka 2.6.x
           scala_version: 2.13.5
           akka_version: 2.6.13

jobs:
  scala:
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      TERM: "dumb"
    parameters:
      scala_version:
        type: string
      akka_version:
        type: string
        default: 2.5.32
    steps:
      - checkout
      - restore_cache:
          key: scala-library-dependencies-{{ checksum "build.sbt" }}-{{ checksum "project/Build.scala" }}-{{ checksum "project/Dependencies.scala" }}
      - run:
          name: Format and test
          command: |
            sbt ++<<parameters.scala_version>> test
      - save_cache:
          paths: [ "~/.m2", "~/.ivy2", "~/.cache/coursier" ]
          key: scala-library-dependencies-{{ checksum "build.sbt" }}-{{ checksum "project/Build.scala" }}-{{ checksum "project/Dependencies.scala" }}
